---
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  name: cluster
spec:
  additionalTrustedCA:
    name: registry-config
  registrySources:
    insecureRegistries:
    - 172.29.172.84:5000
    # blockedRegistries:
    # - untrusted.com
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: registry-config
  namespace: openshift-config
data:
  updateservice-registry: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
