apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  name: cluster
spec:
  # disableAllDefaultSources: true
  sources:
    - disabled: true
      name: certified-operators
    - disabled: true
      name: community-operators
    - disabled: true
      name: redhat-marketplace
    - disabled: true
      name: redhat-operators
