apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config-cluster-image.yaml
- config-update-service.yaml
- cs-filtered-certified.yaml
- cs-filtered-redhat.yaml
- image-content.yaml

# OpenShift Upgrade Operator
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/cincinnati-operator/operator/overlays/v1

# OpenShift Logging
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/cluster-logging/operator/overlays/stable

# Node Feature Discovery - for Nvidia
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/nfd/instance/overlays/only-nvidia
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/nfd/operator/overlays/stable

# OpenShift Pipelines
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/openshift-pipelines-operator-rh/operator/overlays/latest

# OpenShift Serverless
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/serverless-operator/instance/knative-eventing/overlays/default
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/serverless-operator/instance/knative-serving/overlays/default
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/serverless-operator/operator/overlays/stable

# OpenShift Service Mesh
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/servicemeshoperator/operator/overlays/stable

# OpenShift Web Terminal
- web-terminal-tooling.yaml
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/web-terminal/operator/overlays/fast

# Nvidia GPU Operator
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/gpu-operator-certified/instance/overlays/default
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/gpu-operator-certified/operator/overlays/stable

patches:
  - target:
      kind: Subscription
    patch: |-
      - op: replace
        path: /spec/source
        value: filtered-redhat-operators
  - target:
      kind: Subscription
      name: gpu-operator-certified
    patch: |-
      - op: replace
        path: /spec/source
        value: filtered-certified-operators
  - target:
      kind: Subscription
      name: vault-secrets-operator
    patch: |-
      - op: replace
        path: /spec/source
        value: filtered-certified-operators