apiVersion: updateservice.operator.openshift.io/v1
kind: UpdateService
metadata:
  name: update-service-oc-mirror
spec:
  graphDataImage: registry-mirror.svc:5000/disconnected/openshift/graph-image@sha256:dfb37e88fdbaea846267b09fff6709ddaed8eb735e085786b2f3570252ac7cbf
  releases: registry-mirror.svc:5000/disconnected/openshift/release-images
  replicas: 2
