apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-00
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /aimlp_app/ocp1data/pv-00
    server: 192.168.1.40