apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-00
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs