apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
  namespace: mlflow
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: mlflow-server-tls
  labels:
    helm.sh/chart: mlflow-server-0.6.2
    app.kubernetes.io/name: mlflow-server
    app.kubernetes.io/instance: mlflow-server
    app.kubernetes.io/version: "2.6"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: mlflow-server
      protocol: TCP
      name: mlflow-server
    - port: 8443
      targetPort: oauth-proxy
      protocol: TCP
      name: oauth
  selector:
    app.kubernetes.io/name: mlflow-server
    app.kubernetes.io/instance: mlflow-server
