apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/codekow/demo-ai-gitops-catalog/components/configs/kustomized/minio/overlays/with-namespace
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/crunchy-postgres-operator/operator/overlays/v5
- ../../components/configs/kustomized/mlflow/overlays/0.6.2
- link-mlflow.yaml
- link-minio.yaml