apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Advanced Cluster Security
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/advanced-cluster-security/instance/overlays/default
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/advanced-cluster-security/operator/overlays/latest
- demo-route-job.yaml
- link-acs.yaml