apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

# Cluster Login
- https://github.com/codekow/demo-ai-gitops-catalog/components/configs/cluster/login/overlays/htpasswd

# Image Registry Config
- https://github.com/codekow/demo-ai-gitops-catalog/components/configs/cluster/registry/overlays/empty-dir
