---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 4
storageConfig:
  local:
    path: ./mirror_media
  # registry:
  #   imageURL: "localhost:5000"
  #   skipTLS: true
mirror:
  operators:
    - catalog: 'registry.redhat.io/redhat/redhat-operator-index:v4.13'
      packages:
        - name: devspaces
          channels:
            - name: stable
  additionalImages:
    - name: ghcr.io/codekow/web-terminal-tooling:latest
    - name: ghcr.io/redhat-na-ssa/udi-cuda:12.3.2-cudnn9-devel-ubi8-python311
    - name: ghcr.io/redhat-na-ssa/udi-cuda:latest
    - name: ghcr.io/redhat-na-ssa/s2i-cuda:latest
