# openshift platform images
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 4
storageConfig:
  local:
    path: ./scratch/mirror_media
  # registry:
  #   imageURL: "localhost:5000"
  #   skipTLS: false
mirror:
  platform:
    architectures:
      - amd64
    # graph: true
    channels:
    - name: stable-4.13
      type: ocp
      minVersion: 4.13.36
      shortestPath: true
    - name: stable-4.14
      type: ocp
      minVersion: 4.14.18
      shortestPath: true
