# operators from certified partners
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
# archiveSize: 4
storageConfig:
  local:
    path: ./scratch/mirror_media
  # registry:
  #   imageURL: "localhost:5000"
  #   skipTLS: false
mirror:
  operators:
    - catalog: 'registry.redhat.io/redhat/certified-operator-index:v4.13'
      packages:
        # oc mirror list operators --catalog registry.redhat.io/redhat/certified-operator-index:v4.14 --package gpu-operator-certified --channel=stable
        - name: gpu-operator-certified
          channels:
            - name: 'v23.9'
            - name: stable
        # BUG: this operator has a reference to a missing image hash
        - name: nvidia-network-operator
          channels:
            - name: '24.1.1'
            - name: stable
      # targetName: custom-ocp-index
      # targetTag: v4.13.0.0
  # KLUDGE: START
  # BUG: ghcr.io/mellanox/network-operator-init-container@sha256:eab20c1439fc0ff438ef84db9f289bf344db5584f4238cf7384e1d8f1b4982c8: manifest unknown
  additionalImages:
    - name: ghcr.io/mellanox/network-operator-init-container:latest
  blockedImages:
    - name: ghcr.io/mellanox/network-operator-init-container@sha256:eab20c1439fc0ff438ef84db9f289bf344db5584f4238cf7384e1d8f1b4982c8
  # KLUDGE: END