# openshift platform images
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
# archiveSize: 4
storageConfig:
  local:
    path: ./scratch/mirror_media
  # registry:
  #   imageURL: "localhost:5000"
  #   skipTLS: false
mirror:
  operators:
    - catalog: 'registry.redhat.io/redhat/redhat-operator-index:v4.13'
      packages:
        # oc mirror list operators --catalog registry.redhat.io/redhat/redhat-operator-index:v4.14 --package devworkspace-operator --channel=fast
        - name: devworkspace-operator
          channels:
            - name: fast
        - name: cluster-logging
          channels:
            - name: stable-5.9
            - name: stable
        - name: kubernetes-nmstate-operator
          channels:
            - name: '4.13'
            - name: stable
        - name: kubevirt-hyperconverged
          channels:
            - name: stable
        - name: nfd
          channels:
            - name: stable
        - name: openshift-pipelines-operator-rh
          channels:
            - name: pipelines-1.14
            - name: latest
        - name: serverless-operator
          channels:
            - name: stable
        - name: web-terminal
          channels:
            - name: fast
              minVersion: '1.7.0'
        - name: servicemeshoperator
          channels:
            - name: stable
        - name: rhacs-operator
          channels:
            - name: stable
      # targetName: custom-ocp-index
      # targetTag: v4.13.0.0
  # additionalImages:
  # - name: registry.redhat.io/ubi8/ubi:latest
