---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 4
storageConfig:
  local:
    path: ./mirror_media
  # registry:
  #   imageURL: "localhost:5000"
  #   skipTLS: true
mirror:
  # additionalImages:
  #   - name: gcr.io/run-ai-demo/jupyter-demo
  #   - name: nvcr.io/nvidia/pytorch:23.08-py3
  helm:
    repositories:
      - name: runai-backend
        url: https://backend-charts.storage.googleapis.com
        charts:
          - name: control-plane
            version: 2.15.13
      - name: runai
        url: https://run-ai-charts.storage.googleapis.com
        charts:
          - name: runai-cluster
            version: 2.16.30
