# openshift platform images
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
# archiveSize: 4
storageConfig:
  local:
    path: ./scratch/mirror_media
  # registry:
  #   imageURL: "localhost:5000"
  #   skipTLS: false
mirror:
  platform:
    architectures:
      - amd64
    # graph: true
    channels:
    - name: stable-4.13
      type: ocp
      # minVersion: 4.13.36
      # shortestPath: true
    # - name: stable-4.14
    #   type: ocp
    #   minVersion: 4.14.18
  operators:
    - catalog: 'registry.redhat.io/redhat/redhat-operator-index:v4.13'
      packages:
        # oc mirror list operators --catalog registry.redhat.io/redhat/redhat-operator-index:v4.14 --package devworkspace-operator --channel=fast
        - name: devworkspace-operator
          channels:
            - name: fast
        - name: cluster-logging
          channels:
            - name: stable-5.9
            - name: stable
        - name: kubernetes-nmstate-operator
          channels:
            - name: '4.13'
            - name: stable
        - name: kubevirt-hyperconverged
          channels:
            - name: stable
        - name: nfd
          channels:
            - name: stable
        - name: openshift-pipelines-operator-rh
          channels:
            - name: pipelines-1.14
            - name: latest
        - name: serverless-operator
          channels:
            - name: stable
        - name: web-terminal
          channels:
            - name: fast
              minVersion: '1.7.0'
        - name: servicemeshoperator
          channels:
            - name: stable
        - name: rhacs-operator
          channels:
            - name: stable
      # targetName: custom-ocp-index
      # targetTag: v4.13.0.0
    - catalog: 'registry.redhat.io/redhat/certified-operator-index:v4.13'
      packages:
        # oc mirror list operators --catalog registry.redhat.io/redhat/certified-operator-index:v4.14 --package gpu-operator-certified --channel=stable
        - name: gpu-operator-certified
          channels:
            - name: 'v23.9'
            - name: stable
        # BUG: this operator has a reference to a missing image hash
        - name: nvidia-network-operator
          channels:
            - name: '24.1.1'
            - name: stable
      # targetName: custom-ocp-index
      # targetTag: v4.13.0.0
  # KLUDGE: START
  # KLUDGE: ghcr.io/mellanox/network-operator-init-container
  # KLUDGE: manifest sha256:eab20c1439fc0ff438ef84db9f289bf344db5584f4238cf7384e1d8f1b4982c8: manifest unknown
  additionalImages:
    - name: ghcr.io/mellanox/network-operator-init-container:latest
  blockedImages:
    - name: ghcr.io/mellanox/network-operator-init-container@sha256:eab20c1439fc0ff438ef84db9f289bf344db5584f4238cf7384e1d8f1b4982c8
  # KLUDGE: END
  helm:
    repositories:
      - name: runai-backend
        url: https://backend-charts.storage.googleapis.com
        charts:
          - name: control-plane
            version: 2.15.13
      - name: runai
        url: https://run-ai-charts.storage.googleapis.com
        charts:
          - name: runai-cluster
            version: 2.16.30