# openshift platform images
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
# archiveSize: 4
storageConfig:
  local:
    path: ./scratch/mirror_media
  # registry:
  #   imageURL: "localhost:5000"
  #   skipTLS: false
mirror:
  operators:
    - catalog: 'registry.redhat.io/redhat/certified-operator-index:v4.13'
      packages:
        # oc mirror list operators --catalog registry.redhat.io/redhat/certified-operator-index:v4.14 --package gpu-operator-certified --channel=stable
        - name: gpu-operator-certified
          channels:
            - name: v23.9
            - name: stable
        # oc mirror list operators --catalog registry.redhat.io/redhat/certified-operator-index:v4.14 --package nvidia-network-operator --channel=stable
        - name: nvidia-network-operator
          channels:
            - name: '24.1.1'
            - name: stable
      # targetName: custom-ocp-index
      # targetTag: v4.13.0.0
  # additionalImages:
  # - name: registry.redhat.io/ubi8/ubi:latest
