---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 4
storageConfig:
  local:
    path: ./mirror_media
  # registry:
  #   imageURL: "localhost:5000"
  #   skipTLS: true
mirror:
  operators:
    - catalog: 'registry.redhat.io/redhat/redhat-operator-index:v4.13'
      packages:
        # oc mirror list operators --catalog registry.redhat.io/redhat/redhat-operator-index:v4.14 --package advanced-cluster-management --channel=release-2.10
        - name: advanced-cluster-management
          channels:
            - name: release-2.10
        - name: cincinnati-operator
          channels:
            - name: v1
        - name: cluster-logging
          channels:
            - name: stable-5.9
            - name: stable
        # - name: compliance-operator
        #   channels:
        #     - name: stable
        #       minVersion: 1.4.0
        - name: devspaces
          channels:
            - name: stable
        - name: devworkspace-operator
          channels:
            - name: fast
        # - name: kubernetes-nmstate-operator
        #   channels:
        #     - name: stable
        # - name: kubevirt-hyperconverged
        #   channels:
        #     - name: stable
        # - name: multicluster-engine
        #   channels:
        #     - name: stable-2.3
        #     - name: 'v2.3.6'
        - name: nfd
          channels:
            - name: stable
        - name: openshift-gitops-operator
          channels:
            - name: latest
        - name: openshift-pipelines-operator-rh
          channels:
            - name: pipelines-1.14
            - name: latest
        - name: rhacs-operator
          channels:
            - name: stable
        - name: serverless-operator
          channels:
            - name: stable
        - name: servicemeshoperator
          channels:
            - name: stable
        - name: web-terminal
          channels:
            - name: fast
              minVersion: '1.7.0'
      targetName: filtered-redhat-operator-index
      targetTag: v4.13.0.0
  additionalImages:
    - name: registry.redhat.io/openshift4/ose-node-feature-discovery:v4.13
