---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 4
storageConfig:
  local:
    path: ./mirror_media
  # registry:
  #   imageURL: "localhost:5000"
  #   skipTLS: true
mirror:
  operators:
    - catalog: 'registry.redhat.io/redhat/certified-operator-index:v4.13'
      packages:
        - name: crunchy-postgres-operator
          channels:
            - name: 'v5'
        - name: gpu-operator-certified
          channels:
            - name: 'v24.3'
            - name: stable
        # BUG: nvidia-network-operator operator has a reference to a missing image hash
        # - name: nvidia-network-operator
        #   channels:
        #     - name: '24.1.1'
        #     - name: stable
        - name: vault-secrets-operator
          channels:
            - name: stable
      targetName: only-certified-operator-index
      targetTag: v4.13.0.0
  # KLUDGE: START
  # BUG: ghcr.io/mellanox/network-operator-init-container@sha256:eab20c1439fc0ff438ef84db9f289bf344db5584f4238cf7384e1d8f1b4982c8: manifest unknown
  # additionalImages:
  #   - name: ghcr.io/mellanox/network-operator-init-container:latest
  # blockedImages:
  #   - name: ghcr.io/mellanox/network-operator-init-container@sha256:eab20c1439fc0ff438ef84db9f289bf344db5584f4238cf7384e1d8f1b4982c8
  # KLUDGE: END