# red hat supported operators
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 4
storageConfig:
  local:
    path: ./scratch/mirror_media
  # registry:
  #   imageURL: "localhost:5000"
  #   skipTLS: false
mirror:
  operators:
    - catalog: 'registry.redhat.io/redhat/redhat-operator-index:v4.13'
      packages:
        # oc mirror list operators --catalog registry.redhat.io/redhat/redhat-operator-index:v4.14 --package advanced-cluster-management --channel=release-2.10
        - name: nfd
          channels:
            - name: stable
      targetName: nvidia-only-redhat-operator-index
      targetTag: v4.13.0.0
    - catalog: 'registry.redhat.io/redhat/certified-operator-index:v4.13'
      packages:
        # oc mirror list operators --catalog registry.redhat.io/redhat/certified-operator-index:v4.14 --package gpu-operator-certified --channel=stable
        - name: gpu-operator-certified
          channels:
            - name: 'v24.3'
            - name: stable
      targetName: nvidia-only-certified-operator-index
      targetTag: v4.13.0.0
