apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- banner-data.yaml
- link-demo.yaml
- link-runai.yaml
- web-terminal-tooling.yaml

# Run AI
# BUG: currently not installing
# - https://github.com/codekow/demo-ai-gitops-catalog/components/operators/run-ai/operator/overlays/stable

# OpenShift Logging
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/cluster-logging/operator/overlays/stable

# Node Maintenance Operator
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/node-maintenance-operator/operator/overlays/stable

# Nvidia GPU Operator
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/gpu-operator-certified/instance/overlays/default
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/gpu-operator-certified/operator/overlays/stable

# Nvidia Network Operator
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/nvidia-network-operator/operator/overlays/24.1.0

# NmState Operator
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/kubernetes-nmstate-operator/operator/overlays/stable

# OpenShift Virtualization
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/kubevirt-hyperconverged/instance/overlays/default
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/kubevirt-hyperconverged/operator/overlays/stable

# Compliance
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/compliance-operator/operator/overlays/stable

# Loki
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/loki-operator/operator/overlays/stable-5.8

# Node Feature Discovery - for Nvidia
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/nfd/instance/overlays/only-nvidia
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/nfd/operator/overlays/stable

# OpenShift Pipelines
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/openshift-pipelines-operator-rh/operator/overlays/latest

# Red Hat SSO
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/rhsso-operator/operator/overlays/stable

# OpenShift Service Mesh
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/servicemeshoperator/operator/overlays/stable

# OpenShift Web Terminal
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/web-terminal/instance/overlays/enhanced
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/web-terminal/operator/overlays/fast

patches:
  - target:
      kind: ConsoleNotification
      name: banner-demo
    patch: |-
      - op: replace
        path: /spec/text
        value: 'DEMO: Dell CSC Lab'
