---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: custom-0
spec:
  imageDigestMirrors:
  - mirrors:
    - container-proxy/docker-hub-perf
    source: docker.io
  - mirrors:
    - container-proxy/gcr-io
    source: gcr.io
  - mirrors:
    - container-proxy/docker-ghcr-io
    source: ghcr.io
  - mirrors:
    - container-proxy/docker-kube-state-metrics
    source: registry.k8s.io
  - mirrors:
    - container-proxy/docker-nvcr-remote
    source: nvcr.io
  - mirrors:
    - container-proxy/quay-docker-remote
    source: quay.io
---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: redhat-0
spec:
  imageDigestMirrors:
  - mirrors:
    - container-proxy/redhat-docker-remote
    source: registry.access.redhat.com
  - mirrors:
    - container-proxy/docker-openshift-redhat-connect-remote
    source: registry.connect.redhat.com
  - mirrors:
    - container-proxy/docker-openshift-rh-io-remote
    source: registry.redhat.io
---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: release-0
spec:
  imageDigestMirrors:
  - mirrors:
    - container-proxy/docker-openshift-private-remote/openshift-release-dev
    source: quay.io/openshift-release-dev
