apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-server
  namespace: mlflow
  labels:
    helm.sh/chart: mlflow-server-0.6.2
    app.kubernetes.io/name: mlflow-server
    app.kubernetes.io/instance: mlflow-server
    app.kubernetes.io/version: "2.6"
    app.kubernetes.io/managed-by: Helm
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"mlflow-server"}}'
